cc_library(
    name = "resource",
    srcs = ["resource.cc"],
    hdrs = ["resource.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "copy_and_swap",
    hdrs = ["copy_and_swap.h"],
    srcs = ["copy_and_swap.cc"],
    deps = [":resource"],
    visibility = ["//visibility:public"],
)